ci: add audit script
Signed-off-by: Aaron Teo <aaron.teo1@ibm.com>

diff --git a/.github/workflows/ci-audit.yml b/.github/workflows/ci-audit.yml
--- a/.github/workflows/ci-audit.yml
+++ b/.github/workflows/ci-audit.yml
@@ -15,23 +15,24 @@ jobs:
       - name: Audit
         id: audit
         run: |
-          echo "Auditing self-hosted runner: ${{ runner.name }}"
-          echo "Runner OS: ${{ runner.os }}"
-          echo "Runner architecture: ${{ runner.arch }}"
-          echo "$ cat /etc/passwd"
-          if output=$(cat /etc/passwd 2>&1); then
-            echo "FAIL: /etc/passwd should NOT be readable by the runner."
-            exit 1
-          else
-            echo "OK: cat /etc/passwd: $output"
-          fi
+          bash ./ci/audit.sh
+          # echo "Auditing self-hosted runner: ${{ runner.name }}"
+          # echo "Runner OS: ${{ runner.os }}"
+          # echo "Runner architecture: ${{ runner.arch }}"
+          # echo "$ cat /etc/passwd"
+          # if output=$(cat /etc/passwd 2>&1); then
+          #   echo "FAIL: /etc/passwd should NOT be readable by the runner."
+          #   exit 1
+          # else
+          #   echo "OK: cat /etc/passwd: $output"
+          # fi
 
-          echo "$ cat /etc/shadow"
-          if output=$(cat /etc/shadow 2>&1); then
-            echo "FAIL: /etc/shadow should NOT be readable by the runner."
-            exit 1
-          else
-            echo "OK: cat /etc/shadow: $output"
-          fi
-          echo "Listing /tmp directory:"
-          ls -la /tmp
+          # echo "$ cat /etc/shadow"
+          # if output=$(cat /etc/shadow 2>&1); then
+          #   echo "FAIL: /etc/shadow should NOT be readable by the runner."
+          #   exit 1
+          # else
+          #   echo "OK: cat /etc/shadow: $output"
+          # fi
+          # echo "Listing /tmp directory:"
+          # ls -la /tmp
